# Generated by Django 3.2.3 on 2021-05-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_contact_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountpercent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
